name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        architecture: [x64, x86]
        include:
          - os: ubuntu-latest
            x64: linux-x64
            x86: linux-x86
          - os: windows-latest
            x64: win-x64
            x86: win-x86

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x-preview.1'
          dotnet-quality: 'preview'

      - name: Install dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet publish -c Release -r ${{ matrix[matrix.architecture] }} --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=false

      - name: Archive production artifacts (Linux x64/x86)
        if: runner.os == 'Linux'
        run: tar -czvf release-${{ matrix.architecture }}.tar.gz -C SPFSteamroller/bin/Release/net9.0/${{ matrix.architecture == 'x64' && matrix.x64 || matrix.x86 }}/publish .
        shell: bash

      - name: Archive production artifacts (Windows x64/x86)
        if: runner.os == 'Windows'
        run: Compress-Archive -Path SPFSteamroller/bin/Release/net9.0/${{ matrix.architecture }}/publish/* -DestinationPath release-${{ matrix.architecture }}.zip
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ runner.os == 'Linux' && 'linux' || 'win' }}-${{ matrix.architecture }}
          path: ${{ runner.os == 'Linux' && format('release-{0}.tar.gz', matrix.architecture) || format('release-{0}.zip', matrix.architecture) }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: release-linux-x64
          path: ./release

      - name: Download Linux x86 artifact
        uses: actions/download-artifact@v4
        with:
          name: release-linux-x86
          path: ./release

      - name: Download Windows x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: release-win-x64
          path: ./release

      - name: Download Windows x86 artifact
        uses: actions/download-artifact@v4
        with:
          name: release-win-x86
          path: ./release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Linux x64 artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/release-x64.tar.gz
          asset_name: linux-x64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux x86 artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/release-x86.tar.gz
          asset_name: linux-x86.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows x64 artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/release-x64.zip
          asset_name: windows-x64.zip
          asset_content_type: application/zip

      - name: Upload Windows x86 artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/release-x86.zip
          asset_name: windows-x86.zip
          asset_content_type: application/zip
